name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    env:
      platform: azure
      region: us-east-2
      account: 6544711100

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hello, world!"

      - name: "Variable de entorno"
        run: |
          echo "La plataforma es: $platform"
          echo "Region: ${{ env.region }}"
          echo "Cuenta: ${{ env.account }}"